FROM gcr.io/kaniko-project/executor:v1.23.2

RUN apk add --no-cache busybox

RUN apk add --no-cache docker-cli
ENV KANIKO_VERSION=1.23.2
ADD release/linux/amd64/kaniko-docker /kaniko/
ENTRYPOINT ["/kaniko/kaniko-docker"]
